### ISSUE TITLE
References need to be updated

### ISSUE THREAD

**Issue by mrStudent123** [cotag/a2-file-drop#2]
angular2/core now is @angular/core
Also there's some errors "implicitly defined as any" that need an explicit any type.

**Comment by stakach** [comment]
We'll be reviving this project in the next 2-3 months however happy to accept help in the mean time. If you've made these changes, please make a pull request and we'll merge your changes.

**Comment by stakach** [comment]
Had a moment so I've pushed a new version that should resolve this. Let me know if you have any issues. :)

**Comment by mrStudent123** [comment]
Thanks for the quick fix! The references are fine now, but the webstorm typescript compiler still throws a few errors for implicitly defined any types (see attached file), if you explicitly declare them as data : any everything's compiling again.
![errors](https://cloud.githubusercontent.com/assets/19288606/16911034/82f5b70a-4cdc-11e6-9421-fb146a660ffa.png)
